### ISSUE TITLE
Suggestions with aliases so that they can be found faster

### ISSUE THREAD

**Issue by alexanderadam** [yodamad/gitlab-emoji#6]
That's a great idea.
It would be handy to have some 'inspiration' to copy and paste.

Like the example that you show in the screenshot.

For instance

```yaml
build:
  - 📦 
  - 🚧 
 test:
 - 🤞 
 - ✅ 
 ...
```
